package pojos;
// Generated Dec 3, 2018 7:08:52 PM by Hibernate Tools 4.3.1



/**
 * Acara generated by hbm2java
 */
public class Acara  implements java.io.Serializable {


     private String jenisAcara;

    public Acara() {
    }

    public Acara(String jenisAcara) {
       this.jenisAcara = jenisAcara;
    }
   
    public String getJenisAcara() {
        return this.jenisAcara;
    }
    
    public void setJenisAcara(String jenisAcara) {
        this.jenisAcara = jenisAcara;
    }




}


