package pojos;
// Generated Dec 3, 2018 7:08:52 PM by Hibernate Tools 4.3.1



/**
 * Akun generated by hbm2java
 */
public class Akun   implements java.io.Serializable, Comparable<Akun> {


     private int nik;
     private String nama;
     private String email;
     private String password;

    public Akun() {
    }

    public Akun(String email, String password) {       
       this.email = email;
       this.password = password;
    }
    public Akun(int nik, String nama, String email, String password) {
       this.nik = nik;
       this.nama = nama;
       this.email = email;
       this.password = password;
    }
   
    public int getNik() {
        return this.nik;
    }
    
    public void setNik(int nik) {
        this.nik = nik;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public int compareTo(Akun akun) {
        return this.email.compareTo(akun.email);
        }




}


