package pojos;
// Generated Dec 3, 2018 7:08:52 PM by Hibernate Tools 4.3.1

/**
 * DataCalon generated by hbm2java
 */
public class DataCalon implements java.io.Serializable, Comparable<DataCalon> {

    private Integer idDataCalon;
    private int nikCalon;
    private String namaCalon;
    private int noUrut;
    private byte[] foto;
    private String jenisAcara;

    public DataCalon() {
    }
    public DataCalon(String jenisAcara) {
        this.jenisAcara = jenisAcara;
    }

    public DataCalon(int nikCalon, String namaCalon, int noUrut, byte[] foto, String jenisAcara) {
        this.nikCalon = nikCalon;
        this.namaCalon = namaCalon;
        this.noUrut = noUrut;
        this.foto = foto;
        this.jenisAcara = jenisAcara;
    }

    public Integer getIdDataCalon() {
        return this.idDataCalon;
    }

    public void setIdDataCalon(Integer idDataCalon) {
        this.idDataCalon = idDataCalon;
    }

    public int getNikCalon() {
        return this.nikCalon;
    }

    public void setNikCalon(int nikCalon) {
        this.nikCalon = nikCalon;
    }

    public String getNamaCalon() {
        return this.namaCalon;
    }

    public void setNamaCalon(String namaCalon) {
        this.namaCalon = namaCalon;
    }

    public int getNoUrut() {
        return this.noUrut;
    }

    public void setNoUrut(int noUrut) {
        this.noUrut = noUrut;
    }

    public byte[] getFoto() {
        return this.foto;
    }

    public void setFoto(byte[] foto) {
        this.foto = foto;
    }

    public String getJenisAcara() {
        return this.jenisAcara;
    }

    public void setJenisAcara(String jenisAcara) {
        this.jenisAcara = jenisAcara;
    }

    @Override
    public int compareTo(DataCalon dataCalon) {
        return this.jenisAcara.compareTo(dataCalon.jenisAcara);
    }

}
