package pojos;
// Generated Nov 6, 2018 12:49:23 PM by Hibernate Tools 4.3.1



/**
 * DataCalon generated by hbm2java
 */
public class DataCalon  implements java.io.Serializable {


     private int nik;
     private String nama;
     private int noUrut;
     private byte[] foto;

    public DataCalon() {
    }

    public DataCalon(int nik, String nama, int noUrut, byte[] foto) {
       this.nik = nik;
       this.nama = nama;
       this.noUrut = noUrut;
       this.foto = foto;
    }
   
    public int getNik() {
        return this.nik;
    }
    
    public void setNik(int nik) {
        this.nik = nik;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public int getNoUrut() {
        return this.noUrut;
    }
    
    public void setNoUrut(int noUrut) {
        this.noUrut = noUrut;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }




}


