package pojos;
// Generated Dec 3, 2018 7:08:52 PM by Hibernate Tools 4.3.1



/**
 * PesertaAcara generated by hbm2java
 */
public class PesertaAcara  implements java.io.Serializable {


     private Integer idPesertaAcara;
     private int nik;
     private String nama;
     private String jenisAcara;

    public PesertaAcara() {
    }

    public PesertaAcara(int nik, String nama, String jenisAcara) {
       this.nik = nik;
       this.nama = nama;
       this.jenisAcara = jenisAcara;
    }
   
    public Integer getIdPesertaAcara() {
        return this.idPesertaAcara;
    }
    
    public void setIdPesertaAcara(Integer idPesertaAcara) {
        this.idPesertaAcara = idPesertaAcara;
    }
    public int getNik() {
        return this.nik;
    }
    
    public void setNik(int nik) {
        this.nik = nik;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getJenisAcara() {
        return this.jenisAcara;
    }
    
    public void setJenisAcara(String jenisAcara) {
        this.jenisAcara = jenisAcara;
    }




}


