package pojos;
// Generated Nov 6, 2018 12:49:23 PM by Hibernate Tools 4.3.1



/**
 * PesertaAcara generated by hbm2java
 */
public class PesertaAcara  implements java.io.Serializable {


     private int nik;
     private String nama;
     private String namaAcara;

    public PesertaAcara() {
    }

    public PesertaAcara(int nik, String nama, String namaAcara) {
       this.nik = nik;
       this.nama = nama;
       this.namaAcara = namaAcara;
    }
   
    public int getNik() {
        return this.nik;
    }
    
    public void setNik(int nik) {
        this.nik = nik;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getNamaAcara() {
        return this.namaAcara;
    }
    
    public void setNamaAcara(String namaAcara) {
        this.namaAcara = namaAcara;
    }




}


