package pojos;
// Generated Dec 3, 2018 7:08:52 PM by Hibernate Tools 4.3.1



/**
 * Voters generated by hbm2java
 */
public class Voters  implements java.io.Serializable {


     private Integer idVoters;
     private int nik;
     private String nama;
     private int noUrut;
     private String jenisAcara;

    public Voters() {
    }

    public Voters(int nik, String nama, int noUrut, String jenisAcara) {
       this.nik = nik;
       this.nama = nama;
       this.noUrut = noUrut;
       this.jenisAcara = jenisAcara;
    }
   
    public Integer getIdVoters() {
        return this.idVoters;
    }
    
    public void setIdVoters(Integer idVoters) {
        this.idVoters = idVoters;
    }
    public int getNik() {
        return this.nik;
    }
    
    public void setNik(int nik) {
        this.nik = nik;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public int getNoUrut() {
        return this.noUrut;
    }
    
    public void setNoUrut(int noUrut) {
        this.noUrut = noUrut;
    }
    public String getJenisAcara() {
        return this.jenisAcara;
    }
    
    public void setJenisAcara(String jenisAcara) {
        this.jenisAcara = jenisAcara;
    }




}


